language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="<1.5,>=1.4"
  - DJANGO="<1.8,>=1.7"
  - DJANGO="<1.9,>=1.8"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="<1.8,>=1.7"
    - python: "2.6"
      env: DJANGO="<1.9,>=1.8"
    - python: "3.2"
      env: DJANGO="<1.5,>=1.4"
    - python: "3.3"
      env: DJANGO="<1.5,>=1.4"
    - python: "3.4"
      env: DJANGO="<1.5,>=1.4"
    - python: "pypy3"
      env: DJANGO="<1.5,>=1.4"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install Django$DJANGO
  - pip install coveralls
script:
  coverage run --source=vies runtests.py
after_success:
  coveralls
