language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
env:
  - DJANGO="<1.5,>=1.4"
  - DJANGO="<1.8,>=1.7"
  - DJANGO="<1.9,>=1.8"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="<1.5,>=1.4"
    - python: "3.4"
      env: DJANGO="<1.5,>=1.4"
    - python: "pypy3"
      env: DJANGO="<1.5,>=1.4"
install:
  - pip install --upgrade pip
  - pip install .
  - pip install Django$DJANGO
  - pip install coveralls
  - pip install isort
  - pip install flake8
  - pip install pep257
script:
  coverage run --source=vies runtests.py
  flake8 --statistics --show-source vies
  isort -c -rc -df vies
  pep257 --ignore=D100,D101,D102,D103 vies
after_success:
  coveralls
